project:
  type: website

website:
  title: "Blogs and Articles"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/vmandela99/
format:
  html:
    # theme: minty
    theme: materia
    # css: styles.css
    css: custom.scss

editor: visual

execute:
  freeze: true


