project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
  resources:
    - _headers

website:
  # title: "Articles"
  favicon: images/logo.png
  # description: "Data Science and Statistical Consulting"
  open-graph: true
  google-analytics: "GTM-T8DDSMN"
  navbar:
    logo: images/logo.png
    background: "#800080"
    collapse: true
    pinned: true
    left: [] 
    right:
      - icon: list
        menu:
          - text: "Upcoming Courses"
            href: courses/index.qmd
          - text: "Available Course"
            href: courses/available_courses.qmd
          - text: "Gallery"
            href: myworks/gallery.qmd
          - text: "Projects"
            href: myworks/projects.qmd
          - text: "Testimonies/Awards"
            href: myworks/awards.qmd
          - text: "Dashboards/Apps"
            href: myworks/apps.qmd
          - text: "Books"
            href: books/books.qmd
          - text: "Blogs"
            href: index.qmd
          - text: "About"
            href: about.qmd
  # navbar:
  #   logo: images/logo.png
  #   background: "#800080"         # Purple background
  #   collapse: true                # Collapse menu into hamburger icon
  #   pinned: true
  #   left: []                      # Hide default left items
  #   right:
  #     - icon: list
  #       menu:
  #         - text: "Home"
  #           href: index.qmd
  #         - text: "My Courses"
  #           menu:
  #             - text: "Upcoming courses"
  #               href: courses/upcoming_courses.qmd
  #             - text: "Available Course"
  #               href: courses/available_courses.qmd
  #         - text: "My Works"
  #           menu:
  #             - text: "Gallery"
  #               href: myworks/gallery.qmd
  #             - text: "Projects"
  #               href: myworks/projects.qmd
  #             - text: "Testimonies/Awards"
  #               href: myworks/awards.qmd
  #             - text: "Dashboards/Apps"
  #               href: myworks/apps.qmd
  #             - text: "Books"
  #               href: books/books.qmd
  #         - text: "About"
  #           href: about.qmd
format:
  html:
    # theme: minty
    theme: materia
    # css: styles.css
    css: custom.scss

editor: visual

execute:
  freeze: true
  
  


