project:
  type: website

website:
  title: "My Blogs"
  # description: "Data Science and Statistical Consulting"
  open-graph: true
  google-analytics: "GTM-T8DDSMN"
  
  navbar:
    right:
      - about.qmd
      - Projects.qmd
      - Skills.qmd
      - Templates and Resources.qmd
      - Case Study.qmd
      - href: contact/index.qmd
        text: Contact
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/vmandela99/
format:
  html:
    # theme: minty
    theme: materia
    # css: styles.css
    css: custom.scss

editor: visual

execute:
  freeze: true


